### PR TITLE
feat: Creating landing page for [Hulk]

### PR DESCRIPTION
**Pull request by TomiOliva**

### CODE REVIEW

**Review by cerveux — APPROVED** [review]
LGTM

**Review by mhechavarria — CHANGES_REQUESTED** [review]
Please move your files inside your folder

**Comment by TomiOliva** [comment]
> Please move your files inside your folder

"Hi, I have completed the requested changes in this Pull Request."

**Comment by TomiOliva** [comment]
> Please move your files inside your folder
Hi, I have completed the requested changes in this Pull Request.

**Comment by TomiOliva** [comment]
> Please move your files inside your folder
Hi, I have completed the requested changes in this Pull Request.

**Review by mhechavarria — APPROVED** [review]
Thanks for moving the files, you can go ahead and merge it 🙌

**Review by JulianaCotabarren — APPROVED** [review]
LGTM :)

**Pull request merged**
